### PR TITLE
Add README.md inside docs/

### PR DESCRIPTION
**Pull request by Chemaclass**
## 📚 Description

Create a `README.md` to display all assert functions when you go to the `docs/` folder

Screenshot 2023-09-11 at 14 30 57

### CODE REVIEW

**Review by JesusValera — COMMENTED** [review]
As an idea is ok, I like it, but in the case of adding some description next to the `assertXXX`, we could add something more meaningful 🙂

**Comment by khru** [comment]
@Chemaclass I've added to the ``functional/logic_test.sh` all this test

image

Should I put them into the example or we should update the module with the example inside?

**Comment by khru** [comment]
My suggestion for changes would be this: https://github.com/Chemaclass/bashunit/pull/55

**Comment by Chemaclass** [comment]
> As an idea is ok, I like it, but in the case of adding some description next to the `assertXXX`, we could add something more meaningful 🙂

Feel free to add a description in a follow up commit

**Pull request merged**
